# This workflow will build a Java project with Maven
2
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
3
4
name: Java Project with Maven
5
6
on:
7
  push:
8
    branches: [ main ]
9
10
jobs:
11
  build:
12
    runs-on: windows-10
13
14
    steps:
15
    - uses: actions/checkout@v2
16
    - name: Set up Maven Central Repository
17
      uses: actions/setup-java@v1
18
      with:
19
        java-version: 1.8
20
        server-id: ossrh
21
        server-username: MAVEN_USERNAME
22
        server-password: MAVEN_PASSWORD
23
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
24
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
25
    - name: Deploy with Maven
26
      run: mvn -B clean deploy -Pci-cd
27
      env:
28
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
29
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
30
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
